#!/usr/bin/env bash

#!/usr/bin/env bash

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

BASENAME="$(basename $(dirname "$DIR" ) )"

echo "Stopping and deleting containers"
"$DIR"/docker-compose-dev down

echo "Stopping synchronised volumes"
PROJECT_NAME=${BASENAME} docker-sync stop -c "$DIR"/../docker/docker-sync.yml

echo "Removing synchronised volumes"
PROJECT_NAME=${BASENAME} docker-sync clean -c "$DIR"/../docker/docker-sync.yml
