#!/usr/bin/env bash

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

if [[ ! -d public ]]; then
    mkdir -p public
fi

BASENAME="$(basename $(dirname "$DIR" ) )"

echo "Starting synchronised volumes.  Please be patient, this can take some time on first run."
PROJECT_NAME=${BASENAME} docker-sync start -c "$DIR"/../docker/docker-sync.yml

echo "Starting containers"
exec "$DIR"/docker-compose-dev up -d --remove-orphans "$@"
