version: "2"

options:
  verbose: true
  compose-file-path: './docker-compose.yml'
  compose-dev-file-path: './docker-compose-dev.yml'
syncs:
  ${PROJECT_NAME}-appcode-sync: # tip: add -sync and you keep consistent names as a convention
    src: '.'
    sync_userid: '82'
    sync_groupid: '82'
    sync_excludes: ['dev', '.git', 'docker', '.DS_Store', '.gitignore', '.idea', '.docker-sync', '.gitkeep', '*.iml']
    host_disk_mount_mode: 'cached'
  ${PROJECT_NAME}-web-sync:
    src: './public'
    sync_userid: '82'
    sync_groupid: '82'
    host_disk_mount_mode: 'cached'
